import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";

const roboto_Slab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_Slab.className}>
        <main className="max-w-6xl mx-auto p-4">
          <Header />

          {children}
          <footer className="border-t p-8 text-center text-sm mt-12">
            &copy; 2024 All rights reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
